### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by sheim** [sheim/vibly#19]
General code cleanup for using GPs nicely
- [x] dimension-agnostic
- [ ] easily choose active-sampling strategy
- [x] easily forget
- [x] easily adjust parameters

**Comment by sheim** [comment]
Also, add the option to set hard-knowns in the prior (e.g. regions in Q that are known to be safe, and regions in Q that are known to be unsafe). These points should never be forgotten, and should have 0 variance (or at least very very low variance).

**Comment by sheim** [comment]
It would be great if it's easy to compute the kernels separately from the prior. At the moment (if I understand correctly), we're using the same data to do both, which makes sense. I would, however, like to have some examples where we start from a poor prior. When I've tried this, the kernel has totally sucked, and it learns horribly.  

Why is this situation reasonable? The structure of the kernel is something that we should be able to specify from domain knowledge of the system dynamics (we're just being lazy and doing it from data). The prior on the other hand, will often be from a locally stable controller around a linearised point.

**Comment by alexBeuth** [comment]
I don't know what to do with these two points:
1. easily choose active-sampling strategy
We didn't define different strategies yet.

2. easily adjust parameters
What parameters?

**Comment by sheim** [comment]
1. We have so far tried greedy (take safest), or reduce variance (take $a$ with highest variance and above threshold), or closest to the edge (argmin above threshold).

2. safety threshold, and... yeah I guess maybe it's just the safety threshold? I'll take a look at your code in the morning, I think everything else is already exposed...
