### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by sheim** [sheim/vibly#25]
**Benchmark 1** 
Random sampling

**Benchmark 2**
I think a good second benchmark after random-sampling is: do standard BO, except without our measure. Basically, get a value of 1 for a $(s,a)$ that doesn't fail, and 0 for ones that do.

**Comment by alexBeuth** [comment]
For the second one we need a cost function to minimize.

**Comment by sheim** [comment]
Yeah, that should be easy. For the SLIP example, we can just maximize velocity per step or something. For the arbitrary one, we can quite easily define a cost that is not centered around the linearized point.

**Comment by alexBeuth** [comment]
The cost needs to be the measure or at least be a (linear?) transformation of the measure.
I don't see a (easy) BO setting working out as a benchmark. We want to learn the whole function.

**Comment by sheim** [comment]
This is no longer relevant for the paper (outlook)
